# Generated by Django 3.1.4 on 2020-12-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestFramwork', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='book',
            name='author_name',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.TextField(default=None),
        ),
    ]
